name: "Release dev container features & Generate Documentation"
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/checkout@master
      - name: Copy Required Files
        run: |
          mkdir -p src/openpilot/tools
          cp openpilot/update_requirements.sh openpilot/pyproject.toml openpilot/poetry.lock openpilot/.python-version src/openpilot
          cp openpilot/tools/ubuntu_setup.sh openpilot/tools/openpilot_env.sh src/openpilot/tools
      - name: "Publish Features"
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          generate-docs: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
